### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by UsernameDiana** [radeonxray/UFO-Exam#1]
Score: 8

From reading overview, I am looking forward to read further and look forward on the do's and dont's of TypeScript. It also informs the scope of what will follow further in the blog and what the blog will refer to as evidence.

**Comment by ziemerz** [comment]
### Reliable data from credible sources
Score: 6
While the references are clear and the data is in the references, there are a lot of claims in the article like "typescript has a steeper learning curve", which is not backed by any data or investigation.

**Comment by ziemerz** [comment]
### Theoretical explanations
Score: 9
This is not really a theoretical article, but way more practical, which means this is difficult to rate. The theoretical explanations that are there, are quite well explained, but the article feels like it's targeting an audience that are already well acquainted with JavaScript. Words like "bundler" is not explained. 

Other than that, I feel that the explanation is quite good and well defined.

**Comment by ziemerz** [comment]
### Previous work / Future work
Score: 3
While the article definitely discusses previous work, the reflection section does not really reflect on what could have been done differently or discusses another approach one would probably try in future work.

**Comment by radeonxray** [comment]
Addressed the issue by:
- Removed the bullitin of the Abstract and put it in _italic_ 5bc734d8bb85926c25f9f73e56edcf95d4ccaed5
- Reworked the introduction to be shorter, but contain more condensed information 5bc734d8bb85926c25f9f73e56edcf95d4ccaed5
