### ISSUE TITLE
Design Constraints and Assumptions

### ISSUE THREAD

**Issue by UsernameDiana** [radeonxray/UFO-Exam#2]
Score: 7

Examples are provided and explained, but missing more in depth alternatives.

**Comment by radeonxray** [comment]
Addressed the issue by:
- Including a new section "Why TypeScript?", detailing TypeScripts curent place in the programming world. (mentioned as the "2 new charts") 5bc734d
- A new, but very short section "Alternatives", mentioning alternative ways for switching aproject from dynamic typing to static typing in a JS project. 0436232
- Added mention of companies using TypeScript 5bc734d
- Added mention of frameworks supporting TypeScript 5bc734d
