### ISSUE TITLE
DesignCriteria, Sample Calculations and Simulations

### ISSUE THREAD

**Issue by UsernameDiana** [radeonxray/UFO-Exam#3]
Score: 7

samples are provided, explained and reflected upon, except the "tree shaking" feature, nice picture thou :D

**Comment by radeonxray** [comment]
Issue has been addressed by:
- We've removed the section/mention of the "tree shaking" feature, due to realization, that it more of a genral ECMAScript2015-feature, rather than a TypeScript one. 91b833aaabaa317e3612d980b89eb6c737f7101c
