### ISSUE TITLE
Reliable data from credible sources

### ISSUE THREAD

**Issue by ziemerz** [radeonxray/UFO-Exam#4]
Score: 7
While the references are clear and the data is in the references, there are a claim in the article: "typescript has a steeper learning curve", which is not backed by any data or investigation other than it affected the writers project in some way.
Also, some of the sources are tutorials which fails to back the claims made.

**Comment by radeonxray** [comment]
How we are going to address the issue:

- Review all of our sources and make sure, that the ones that are more tutorial/guide are credible enough to withstand scrutiny.
- If "claims" such as the example given can't be backed-up by sources or references, then it is removed or reworked.

**Comment by radeonxray** [comment]
All sources have been updated and case is closed
