### ISSUE TITLE
Previous work / Future work

### ISSUE THREAD

**Issue by ziemerz** [radeonxray/UFO-Exam#6]
Score: 3
While the article definitely discusses previous work, the reflection section does not really reflect on what could have been done differently or discusses another approach one would probably try in future work.

**Comment by radeonxray** [comment]
This was the lowest scoring issue, and has been addressed by:
- Including a new section "Why TypeScript?", detailing TypeScripts curent place in the programming world. (mentioned as the "2 new charts") 5bc734d8bb85926c25f9f73e56edcf95d4ccaed5
- A new, but very short section "Alternatives", mentioning alternative ways for switching aproject from _dynamic typing_ to _static typing_ in a JS project. 043623295c303ba2c7494d059880aaf52cb7b130
- Conclusion has been rewritten 0d36e965f6e3af5db131abee77ba6fe22f8c4d23
- Reflection has been rewritten 9d14c423e28f0b79ccd73a054125bcbc812734d7
- Added mention of companies using TypeScript  5bc734d8bb85926c25f9f73e56edcf95d4ccaed5
- Added mention of frameworks supporting TypeScript 5bc734d8bb85926c25f9f73e56edcf95d4ccaed5
